<?php
$_helper = $this->helper('catalog/output');
$_product = $this->getProduct();
?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div class="quick-view">
    <?php echo $this->getChildHtml('media') ?>

    <a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->__('View Full Details') ?></a>

    <?php echo $this->getReviewsSummaryHtml($_product) ?>

    <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>

    <?php echo $this->getPriceHtml($_product) ?>

    <?php if(!$_product->isSaleable()): ?>
        <div id="availability"><?php echo $this->__('Out Of Stock') ?></div>
    <?php endif; ?>

    <?php echo $this->getChildHtml('alert_urls') ?>
    <div class="product-type-data">
        <?php echo $this->getChildHtml('product_type_data') ?>
    </div>
    <?php echo $this->getTierPriceHtml() ?>
    <?php echo $this->getChildHtml('extrahint') ?>
    <?php echo $this->getChildHtml('other') ?>

    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="order-form" <?php if($_product->getOptions()): ?>enctype="multipart/form-data"<?php endif; ?>>
        <?php if($_product->isSaleable()): ?>
            <?php if($this->hasOptions()): ?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
            <?php endif; ?>
            <?php echo $this->getChildHtml('addtocart') ?>
        <?php endif; ?>
    </form>
</div>
<script type="text/javascript">
    var productAddToCartForm = new VarienForm('order-form');
    productAddToCartForm.submit = function(button, url) {
        if (this.validator.validate()) {
            var form = this.form;
            var oldUrl = form.action;

            if (url) {
                form.action = url;
            }

            var e = null;
            this.form.action = oldUrl;
            form.submit();

            if (e) {
                throw e;
            }

            if (button && button != 'undefined') {
                button.disabled = true;
            }

            return false;
        }
    }.bind(productAddToCartForm);
</script>