<?php
/**
 * Atwix
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.

 * @category    Atwix Mod
 * @package     Atwix_Tweaks
 * @author      Atwix Core Team
 * @copyright   Copyright (c) 2012 Atwix (http://www.atwix.com)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @var $this Atwix_Tweaks_Block_Adminhtml_System_Config_Form_Button
 */
?>
<style>
#row_onebyone_info_shippingmapping{
display:none;	
}

</style>
<script type="text/javascript">
    //<![CDATA[
    function check() {
        new Ajax.Request('<?php echo $this->getAjaxCheckUrl() ?>', {
            method:     'get',
            onSuccess: function(transport){
				if (transport.responseText){
					ft = transport.responseText;
					var bagEle = new Element('div');
					bagEle.update(ft);
					var Content = bagEle.select('div#anchor-content')[0];
					var parentGuest = document.getElementById("config_edit_form");	
					var childGuest = document.createElement("div");
					childGuest.id="collector";
					if (parentGuest.nextSibling) {
					  parentGuest.parentNode.insertBefore(childGuest, parentGuest.nextSibling);
					}
					else {
					  parentGuest.parentNode.appendChild(childGuest);
					}
					
					$$('#collector')[0].innerHTML=Content.innerHTML;
					
				}
            }
        });
    }
	
	function mapp() {
		formaction=document.getElementById("mapping_form").action;
		new Ajax.Request(formaction, {
            method:     'post',
			parameters: Form.serialize("mapping_form"),
            onSuccess: function(transport){
				window.location.reload();
				if (transport.responseText){
					
					window.location.reload();
					//document.getElementById("messages")[1].innerHTML="Mapping Data is Saved";					
				}
            }
        });
    }
	
	function addFieldMapping()
	{
		var entityType = $('profile_entity_type').value;
		Element.insert($('map_container_'+entityType), {bottom: $('map_template_'+entityType).innerHTML});
	}
	function removeFieldMapping(button)
	{
		Element.remove(button.parentNode);
	}
	function setMapFileField(select)
	{
		select.parentNode.getElementsByTagName('input')[0].value = select.value;
	}
    //]]>
</script>

<?php echo $this->getButtonHtml() ?>
