<div class="footer-container">
    <div class="footer" >
        <hr style="border: .1em solid;">

        <div class="container">


            <div class="row">

                <div class="col-lg-offset-3 col-lg-6 col-md-offset-3 col-md-6 col-sm-offset-3 col-sm-7 col-xs-offset-3 col-xs-5 text-center" >
                    <?php echo $this->getChildHtml('cart_footer') ?>

                </div>
            </div>
        </div>

    </div>
</div>
