


<div class="AccC">
<?php echo $this->getMessagesBlock()->toHtml() ?>
<form class="required" action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validates" autocomplete="off">
    <div><input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" /></div>
    <div class="block-title text-left" >
        <h4 class="CcSubheader"><strong><?php echo $this->__('Change Password'); ?></strong></h4>
    </div>
    <div class="my_account control disable" >
        <input type="checkbox "  name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>" checked="checked" class="checkbox disable" /><label for="change_password" class="legend"><?php echo $this->__('Change Password') ?></label>
    </div>
    <div class="my_account "  >

<div class="personal-info ">
    <div class="topping"  >
                <div class="row Fname topping"  >
                    <div class="col-lg-5 col-md-5 col-sm-6 col-xs-5 text-right" >
                    <label for="current_password" class="required" ><em>*</em><?php echo $this->__('Initial Password :') ?></label>
                    </div>
                    <!-- This is a dummy hidden field to trick firefox from auto filling the password -->
                    <div class="col-xs-offset-2  ">
                    <input type="text" class="input-text no-display required" name="dummy" id="dummy" />
                    <input type="password" title="<?php echo $this->__('Current Password') ?>" class="xxsmlchngpwd input-text required-entry" name="current_password" id="current_password" />
                    </div>
                </div>


                <div class=" row Fname topping" >
                    <div class="col-lg-5 col-md-5 col-sm-6 col-xs-5 text-right">
                    <label for="password" class="required" ><em>*</em><?php echo $this->__('New Password :') ?></label>
                    </div>
                        <div class="col-xs-offset-2 ">
                        <input type="password" title="<?php echo $this->__('New Password') ?>" class="xxsmlchngpwd required input-text validate-password required-entry " name="password" id="password"  />
                        </div>
                </div>

                <div class="row Fname topping bottomsp" >
                    <div class="col-lg-5 col-md-5 col-sm-6 col-xs-5 text-right ">
                    <label for="confirmation" class="required" ><em>*</em><?php echo $this->__('Retype New Password :') ?></label>
                    </div>
                        <div class="col-xs-offset-2 ">
                        <input type="password" title="<?php echo $this->__('Confirm New Password') ?>" class="xxsmlchngpwd required input-text validate-cpassword " name="confirmation" id="confirmation" />
                        </div>
                </div>
    </div>
    <div class="buttons-set text-center Accmargindb toppingpr ">
        <p class="required" ><?php echo $this->__('* Required Fields') ?></p>
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="required Artybutton "><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>

</div>

    </div>

</form>
</div>

    <script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validates', true);
    function setPasswordForm(arg){
        if(arg){
            $('current_password').up(3).show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('current_password').up(3).hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }

    <?php if($this->getCustomer()->getChangePassword()): ?>
    setPasswordForm(true);
    <?php endif; ?>
    //]]>
</script>
