

<?php echo $this->getMessagesBlock()->toHtml() ?>



<form class="required" action="<?php echo $this->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" autocomplete="off">
    <div><input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" /></div>

    <div class="my_account control">
        <input type="checkbox" style="display:none" name="change_password" id="change_password" value="1" onclick="setPasswordForm(this.checked)" title="<?php echo $this->__('Change Password') ?>" checked="checked" class="checkbox" /><label for="change_password" class="legend"><?php echo $this->__('Change Password') ?></label>
    </div>
    <div class="my_account "  >

<div class="personal-info">
    <div class="rowspan" >
                <div class="row rowspan" >
                    <div class="col-lg-5 col-md-5 col-sm-6 col-xs-5 text-right xsscreen" >
                    <label for="current_password" class="required" ><em>*</em><?php echo $this->__('Initial Password') ?></label>
                    </div>
                    <!-- This is a dummy hidden field to trick firefox from auto filling the password -->
                    <div class=" ">
                    <input type="text" class="input-text no-display required xstextbx" name="dummy" id="dummy" />
                    <input type="password" title="<?php echo $this->__('Current Password') ?>" class="xstextbx input-text" name="current_password" id="current_password" />
                    </div>
                </div>


                <div class=" row rowspan" >
                    <div class="col-lg-5 col-md-5 col-sm-6 col-xs-5 text-right xsscreen">
                    <label for="password" class="required" ><em>*</em><?php echo $this->__('New Password') ?></label>
                    </div>
                        <div class=" ">
                        <input type="password" title="<?php echo $this->__('New Password') ?>" class="xstextbx required input-text validate-password" name="password" id="password"  />
                        </div>
                </div>

                <div class="row rowspan" >
                    <div class="col-lg-5 col-md-5 col-sm-6 col-xs-5 text-right xsscreen">
                    <label for="confirmation" class="required" ><em>*</em><?php echo $this->__('Retype New Password') ?></label>
                    </div>
                        <div class=" ">
                        <input type="password" title="<?php echo $this->__('Confirm New Password') ?>" class="xstextbx required input-text validate-cpassword" name="confirmation" id="confirmation" />
                        </div>
                </div>
    </div>
    <div class="buttons-set text-center " style="padding-top: 5%;">
        <p class="required" ><?php echo $this->__('* Required Fields') ?></p>
        <button type="submit" title="<?php echo $this->__('Save') ?>" class="required Artybutton "><span><span><?php echo $this->__('Save') ?></span></span></button>
    </div>
    <p><a href="<?php echo $this->escapeUrl($this->getBackUrl()) ?>"><small>&laquo; </small><?php echo $this->__('Back') ?></a></p>

</div>

    </div>

</form>
<script type="text/javascript">
    //<![CDATA[
    var dataForm = new VarienForm('form-validate', true);
    function setPasswordForm(arg){
        if(arg){
            $('current_password').up(3).show();
            $('current_password').addClassName('required-entry');
            $('password').addClassName('required-entry');
            $('confirmation').addClassName('required-entry');

        }else{
            $('current_password').up(3).hide();
            $('current_password').removeClassName('required-entry');
            $('password').removeClassName('required-entry');
            $('confirmation').removeClassName('required-entry');
        }
    }

    <?php if($this->getCustomer()->getChangePassword()): ?>
    setPasswordForm(true);
    <?php endif; ?>
    //]]>
</script>
