<?php
/**
 * Created by PhpStorm.
 * User: sneha
 * Date: 11/2/16
 * Time: 3:02 PM
 */
?>
<div class="AccC" xmlns="http://www.w3.org/1999/html">
    <div class="block-title text-left" >
        <h4 class="CcSubheader"><strong><?php echo $this->__('Notifications'); ?></strong></h4>
    </div>
    <div class=" hotsell " >
        <div class="text-left paddngLeft rowspan">
        <input  type="checkbox" name="vehicle" checked> Email Notifications<br>
        <input  type="checkbox" name="vehicle" checked> Mobile Notification<br>
        <input  type="checkbox" name="vehicle" checked> Web Account Notification<br><br>
        </div>
    </div>
</div>
