<?php ?>
<style>
    .atlas-contactus {
        background:#EAF0EE url(<?php echo $this->getSkinUrl('atlas/atlas.png') ?>) no-repeat scroll 5px center;
        border:1px solid #CCCCCC;
        margin-bottom:10px;
        padding:10px 5px 5px 249px;
        background-size:302px 103px;
    }
    .atlas-text{padding: 26px 0 0 0;}
    .atlas-text h4, .atlas-text p {
        margin:0;
        margin-left: 74px;
    }
    .atlas-text h2 {
        color:#444444;
        font-size:1.4em;
        line-height:1em;
    }
    .atlas-text a {
        text-decoration:none;
    }

    .save {
        display: none;
    }	
</style>
<div class="atlas-contactus">
    <div class="atlas-text">
     <!--<h4><?php echo Mage::helper('adminhtml')->__('Atlas SoftWeb Pvt. Ltd.') ?></h4>-->
        <p><a target="_blank" href="http://atlassoftweb.com/contact-us/"><?php echo Mage::helper('adminhtml')->__('Contact us!') ?></a></p>
        <p>Email :- <a href="mailto:helpdesk@atlassoftweb.com">helpdesk@atlassoftweb.com</a> </p>
        <p>&nbsp</p>
        <p>&nbsp</p>            
    </div>
</div>