

<style>

    .imgF {
        width: 100%;
        height: 100%;
    }


    figure {
        margin: 0;
        padding: 0;
        height: 100%;
        position: relative;
        display: block;
        cursor: pointer;
        overflow: hidden;
        border: 3px solid #fff;

    }

    figure:hover figcaption {
        -ms-filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=100);
        filter: alpha(opacity=100);
        opacity: 1;
        top: 0;
    }

    figcaption {
        -ms-filter: progid:DXImageTransform.Microsoft.Alpha(Opacity=0);
        filter: alpha(opacity=0);
        opacity: 0;
        position: absolute;
        height: 100%;
        width: 100%;
        background: rgba(0,0,0,.5);
        color: #fff;
        -webkit-transition: all .5s ease;
        -moz-transition: all .5s ease;
        -o-transition: all .5s ease;
        -ms-transition: all .5s ease;
        transition: all .5s ease;
        -webkit-transition-delay: .5s;
        -moz-transition-delay: .5s;
        -o-transition-delay: .5s;
        -ms-transition-delay: .5s;
        transition-delay: .5s;
    }

    figcaption h3
    {
        font-size: 30px;
        color: #f3b204;
        padding: 10px 20px;
        margin-bottom: 0;
        position: relative;
        righ: 100%;
        margin-top: 37px;

    }

    figcaption p {
        font-size: 13px;
        padding: 10px 20px;
        background-color: black;
        margin-bottom: 0;
        margin-top: 20px;
        position: relative;
        left: 100%;

    }

    figure:hover h3,figure:hover p {
        left: 0;
    }

    figcaption a {
        color: #fff;
        border: 2px solid #fff;
        padding: 4px 10px;
        text-decoration: none;
    }

    figcaption a:hover {
        color: #4f5856;
        background: #fff;
    }

    @media (max-width: 991px)
    {
        figcaption h3
        {
            font-size: 12px;
        }
        figcaption p
        {
            font-size:12px;
        }
    }

    @media (max-width: 681px) and (min-width: 650px)
    {
        figcaption h3
        {
            font-size: 10px;
        }
        figcaption p
        {
            font-size:10px;
        }
    }

    @media (max-width: 651px)
    {
        figcaption h3
        {
            font-size: 10px;
        }
        figcaption p
        {
            font-size:8px;
        }
    }
    @media (max-width: 480px)
    {
        figcaption h3
        {
            display:none;
        }
        figcaption p
        {
            display: none;
        }
    }

</style>
<?php $_products = $this->getProductCollection(); ?>
<?php $_collectionSize = sizeof($_products); ?>
<?php $_columnCount = Mage::getStoreConfig('homepage/options/count'); ?>


<div class="block block-homepage">
    <div class="row firstH" style="color:white;">
        <span class=""><?php echo $this->getTitle(); ?></span>
    </div>


    <?php if (sizeof($_products)): ?>
        <div class="row subcontent">
            <div class="col-md-12">
                <div class="row">
                    <?php foreach ($_products->getItems() as $_product): ?>

                        <div class="products-grid">


                            <?php // echo $_product->getData('is_salable') . Mage::getStoreConfig('homepage/options/salable');  ?>
                            <?php if ($_product->getData('is_salable')): ?>

                                <div class=" col-lg-6 col-md-6 col-sm-6 col-xs-12 subpadding">
                                    <a href="<?php echo $_product->getProductUrl() ?>">

                                        <figure>
                                        <img class="lightborder img img-responsive"  style="border: solid black"
                                             src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(280) ?>"
                                             alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>"/>
                                            <figcaption>
                                                <h3>I like it!</h3>
                                                <p><?php echo $_product->getName() ?></p>
                                            </figcaption>
                                        </figure>
                                    </a>
                                </div>

                            <?php else: ?>
                                <?php if (Mage::getStoreConfig('homepage/options/salable')) : ?>

                                    <div class=" col-lg-6 col-md-6 col-sm-6 col-xs-12 subpadding">

                                        <a href="<?php echo $_product->getProductUrl() ?>">
                                            <figure>
                                            <img class="lightborder img img-responsive"  style="border: solid black"
                                                 src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(280) ?>"
                                                 alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>"/>
                                                <figcaption>
                                                    <h3>I like it!</h3>
                                                    <p><?php echo $_product->getName() ?></p>
                                                </figcaption>
                                            </figure>

                                        </a>
                                    </div>

                                <?php endif; ?>
                            <?php endif; ?>


                        </div>

                    <?php endforeach; ?>
                </div>
            </div>
        </div>

    <?php else: ?>
        <ol id="bestseller-sidebar" class="mini-products-list">
            <li class="item odd">
                <?php echo Mage::getStoreConfig('homepage/options/noproduct') ?>
            </li>
        </ol>
    <?php endif; ?>


</div>
