<?php $_products = $this->getProductCollection(); ?>
<?php $_collectionSize = sizeof($_products); ?>
<?php $_columnCount = Mage::getStoreConfig('homepage/options/count'); ?>


<div class="block block-homepage">
    <div class="row secondH header2pd Hpaddnglft" style="color:black;">
        <span><?php echo $this->getTitle(); ?></span>
    </div>


    <?php if (sizeof($_products)): ?>
        <div class="row subcontent">
            <div class="col-md-6 col-sm-6 col-xs-12">
                <div class="row">

                    <?php $i = 0;
                    foreach ($_products->getItems() as $_product): ?>

                        <div class="products-grid">


                            <?php // echo $_product->getData('is_salable') . Mage::getStoreConfig('homepage/options/salable');  ?>
                            <?php if ($_product->getData('is_salable')): ?>
                                <div class=" col-lg-6 col-md-6 col-sm-6 col-xs-6 wellpdmg">
                                    <a href="<?php echo $_product->getProductUrl() ?>">
                                        <figure>
                                            <img class="lightborder img img-responsive"
                                                 src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(280) ?>"
                                                 alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>"/>
                                            <figcaption>
                                                <h3>I like it!</h3>

                                                <p><?php echo $_product->getName() ?></p>
                                            </figcaption>
                                        </figure>
                                    </a>
                                </div>
                            <?php else: ?>
                                <?php if (Mage::getStoreConfig('homepage/options/salable')) : ?>
                                    <div class=" col-lg-6 col-md-6 col-sm-6 col-xs-6 wellpdmg">
                                        <a href="<?php echo $_product->getProductUrl() ?>">

                                            <figure>
                                                <img class="lightborder img img-responsive"
                                                     src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(280) ?>"
                                                     alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>"/>
                                                <figcaption>

                                                    <p><?php echo $_product->getName() ?></p>
                                                </figcaption>
                                            </figure>
                                        </a>
                                    </div>
                                <?php endif; ?>
                            <?php endif; ?>

                        </div>

                    <?php endforeach; ?>

                </div>
            </div>
            <?php if ($_product->getData('is_salable')): ?>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 wellpdmg">

                    <a href="<?php echo $_product->getProductUrl() ?>">
                        <figure >
                            <img class="lightborder  img img-responsive"
                                 src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(572) ?>"

                                 alt="<?php echo $this->stripTags($_product->getName(), null, true) ?>"/>
                            <figcaption>


                                <p><?php echo $_product->getName() ?></p>
                            </figcaption>
                        </figure>
                    </a>

                </div>
            <?php endif; ?>
        </div>
    <?php else: ?>
        <ol id="bestseller-sidebar" class="mini-products-list">
            <li class="item odd">
                <?php echo Mage::getStoreConfig('homepage/options/noproduct') ?>
            </li>
        </ol>
    <?php endif; ?>


</div>
