<?php if (Mage::getStoreConfig('ajax_search/general/enabled')) :?>
<style>
.autocomplete strong{color:<?php echo Mage::getStoreConfig('ajax_search/general/keywordcolor') ?> !important;}
</style>
<form id="search_mini_form" action="<?php echo $this->helper('catalogSearch')->getResultUrl() ?>" method="get">
    <fieldset>
        <legend><?php //echo $this->__('Search Site') ?></legend>
        <div class="mini-search form-search">
            <div id="searchajaxico" class=""></div>
            <label for="search"><?php //echo $this->__('Search:') ?></label>
            <?php if (Mage::getStoreConfigFlag('ajax_search/general/show_category_filter')) : ?>
                <?php echo $this->getChildHtml('ajaxsearch_category_filter') ?>
            <?php endif; ?>
            <input id="search" type="text" class="input-text" name="<?php echo $this->helper('catalogSearch')->getQueryParamName() ?>" value="<?php echo Mage::getStoreConfig('ajax_search/general/searchfieldtext'); ?>" style="width:<?php echo Mage::getStoreConfig('ajax_search/general/searchfieldwidth'); ?>px !important;height:<?php echo Mage::getStoreConfig('ajax_search/general/searchfieldheight'); ?>px !important;"/>
            <button type="button" title="<?php echo $this->__('Search') ?>" class="button search-button"><span><span><?php echo $this->__('Search') ?></span></span></button>
        </div>
    </fieldset>
</form>
<script type="text/javascript">
//<![CDATA[
    <?php $_isSecure = $this->getRequest()->isSecure(); ?>
    function initAutocomplete(){
        new Autocomplete('search', {
            serviceUrl   : '<?php echo $this->getUrl('ajaxsearch', array('_secure' => $_isSecure)); ?>',
            enableloader : <?php echo Mage::getStoreConfig('ajax_search/general/enableloader') ? 'true' : 'false'; ?>,
            minChars     : <?php echo Mage::getStoreConfig('ajax_search/general/minchars'); ?>,
            maxHeight    : <?php echo Mage::getStoreConfig('ajax_search/general/maxheight'); ?>,
            width        : <?php echo Mage::getStoreConfig('ajax_search/general/width'); ?>,
            searchtext   : '<?php echo Mage::getStoreConfig('ajax_search/general/searchfieldtext'); ?>',
            onSelect     : function (value, data) {setLocation(value.url);}
        });
    }
    if (Prototype.Browser.IE) {
        Event.observe(window, 'load', initAutocomplete);
    } else {
        document.observe("dom:loaded", initAutocomplete);
    }
//]]>
</script>
<?php endif; ?>