<?php
$category = Mage::getSingleton('catalog/layer')->getCurrentCategory();

$categories = $category->getCollection()
    ->addAttributeToSelect(array('name', 'thumbnail'))
    ->addAttributeToFilter('is_active', 1)
    ->addIdFilter($category->getChildren())
?>
<div class="subcategories">

    <ul class="clearfix">
        <!-- Display Each Subcategory Image and Name  -->

        <?php foreach ($categories as $category): ?>



            <!--  Products from within each subcategory  -->
            <?php
            $_helper = $this->helper('catalog/output');
            $products = Mage::getModel('catalog/product')
                ->getCollection()
                ->addCategoryFilter($category)
                ->addAttributeToSelect(array('name', 'product_url', 'small_image'))
                ->load();

            ?>
            <div class="widget widget-new-products widget-center">

                <div class="widget-products widget-container" style="margin: 0 0 0 10%">
                    <?php echo $this->getPagerHtml() ?>

                    <!-- Display Each product's detailed info  -->
                    <?php foreach ($products->getItems() as $product): ?>


                            <div class="row float">
                                <div class="list-group category-products float">
                                    <div class="grid12-3 align-center " >
                                        <a href="<?php echo $category->getUrl() ?>" class="clearfix">
                                            <?php if ($thumbFile = $category->getThumbnail()): ?>
                                                <img
                                                    src="<?php echo Mage::getBaseUrl('media') . 'catalog' . DS . 'category' . DS . $thumbFile; ?>"
                                                    alt="<?php echo $this->htmlEscape($category->getName()) ?>"/>
                                            <?php endif; ?>
                                            <h4 style="margin-left: 35%" class="align-center"><?php echo $category->getName() ?></h4>
                                        </a>
                                    </div>

                                    <div class="product-img-box" >
                                        <?php // Product Image ?>
                                        <a href="<?php echo $product->getProductUrl() ?>"
                                           title="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>"
                                           class="product-image lightborder">
                                            <img
                                                src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(200); ?>"
                                                width="292" height="290"
                                                alt="<?php echo $this->stripTags($this->getImageLabel($product, 'small_image'), null, true) ?>"/></a>
                                        <?php // Product description ?>
                                        <div >

                                            <div class="row pricerow">
                                                <div class="col-lg-8">
                                                    <h3 class="list-group-item-heading product-description"><a
                                                            href="<?php echo $product->getProductUrl() ?>"
                                                            title="<?php echo $this->stripTags($product->getName(), null, true) ?>)"><?php echo $this->helper('catalog/output')->productAttribute($product, $product->getName(), 'name') ?></a>
                                                    </h3>
                                                </div>
                                                <div class="col-lg-4 categryprice">

                                                        <?php
                                                        $product->getId();
                                                        $_product = Mage::getModel('catalog/product')->load($product->getId());


                                                        $_formattedActualPrice = Mage::helper('core')->currency($_product->getPrice(),true,false);
                                                        $_formattedSpecialPrice = Mage::helper('core')->currency($_product->getFinalPrice(),true,false);

                                                        if($_formattedActualPrice===$_formattedSpecialPrice)
                                                        {
                                                            echo "<br/>".$_formattedActualPrice;

                                                        }
                                                        else
                                                        {
                                                            echo "<br/>"."Actual Price : " .$_formattedActualPrice."<br/>";
                                                            echo "Special Price : ".$_formattedSpecialPrice;
                                                        }

                                                        ?>

                                                </div>
                                            </div>


                                            <div class="list-group-item-text" >

                                                <div class="row swatchesrow" >
                                                <div class="swatches" >
                                                    <?php $swatchproductids=$product->getRelatedProductIds();
                                                    if(empty($swatchproductids))
                                                    {
                                                        $swatchproductids = $product->getUpSellProductIds();
                                                    }
                                                    if(empty($swatchproductids))
                                                    {
                                                        $swatchproductids = $product->getCrossSellProductIds();
                                                    }
                                                    $productcount= count($swatchproductids);
                                                    $i=0;
                                                    foreach($swatchproductids as $swatchproductid):
                                                    $obj = Mage::getModel('catalog/product');
                                                        $i++;
                                                        ?>

                                                    <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 align-center">

                                                        <?php

                                                        if($i< 3) :?>

                                                        <?php
                                                            $_productr = $obj->load($swatchproductid);?>

                                                        <a href="<?php echo $_productr->getProductUrl();?>" class="thumbnail box-border Hpadding swatch-back">
                                                            <img src="<?php echo $this->helper('catalog/image')->init($_productr, 'small_image')->resize(70) ?>" width="90" height="100" alt="<?php echo $this->stripTags($_productr->getName(), null, true) ?>" />
                                                        </a>
                                                        <?php elseif($i==3):?>

                                                            <div class="thumbnail box-border Hpadding vbottom text-center" style="width:83px;height:80px; padding: 26%;">
                                                                <?php echo "<b>".$productcount."</b>"."<br/>"."items";?>
                                                        </div>

                                                        <?php endif; ?>
                                                    </div>


                                                 <?php endforeach;?>



                                                </div>

                                            </div>
                                             <div class="row product-owner ">
                                                <div class="col-lg-2 product-category-profile" style="border: 1px solid black">

                                                </div>
                                                <div class="col-lg-6 col-lg-offset-4">
                                                    <?php
                                                    /**
                                                     * Instanciate reviews helper
                                                     */
                                                    $this->_reviewsHelperBlock = $this->getLayout()->createBlock('review/helper');

                                                    /**
                                                     * Get products for your category
                                                     */

                                                    /**
                                                     * Loop thru products
                                                     */


                                                        /**
                                                         * Display review summary with stars.
                                                         * If correctly configured in back-office: Catalog > Reviews and Ratings > Manage Ratings
                                                         */
                                                      echo   $this->_reviewsHelperBlock->getSummaryHtml($product, false, false);

                                                    ?>

                                                </div>
                                                <div class="col-lg-3">

                                                </div>
                                            </div>

                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                    <?php endforeach; ?>
                </div>
            </div>
        <?php endforeach; ?>
    </ul>
</div>

